### ISSUE TITLE
ngrok + local SIG 

### ISSUE THREAD

**Issue by simachenko** [VladimirKhil/SI#136]
Can i use ngrok to pass my local si game port in the world? If true, can you give me a tips on how to do it correctly?

**Comment by VladimirKhil** [comment]
Hi! I think it is not possible. The game operates main and media ports (usually 7000 and 6999) and creates multimedia links having 6999 port. You can tunnel these ports through ngrok but after that in-game media links will become invalid. To solve the problem the game should use single port for all its operations (that is in the plans but not done yet).
If you want to play across Internet, the best option is to connect to Game Server.
