### ISSUE TITLE
Переход на .NET MAUI?

### ISSUE THREAD

**Issue by te9c** [VladimirKhil/SI#149]
Добрый день.
Планируется ли переход на .NET MAUI для создания кроссплатформенного десктопного приложения SIGame под Linux/MacOS?

**Comment by VladimirKhil** [comment]
Добрый!
В настоящий момент таких планов нет. Упор делается на веб-версию для поддержки кроссплатформенности (с возможным использованием Electron.NET в дальнейшем).
Но логика приложения отделена от представления, так что любой желающий может этим заняться.

**Comment by VladimirKhil** [comment]
В конечном итоге после изучения всех существующих технологий я пришёл к тому, что эффективнее всего использовать связку Avalonia + Web.
MAUI не поддерживает Linux.
