### ISSUE TITLE
Не работает импорт из базы вопросов в SIQuester

### ISSUE THREAD

**Issue by comsomisha** [VladimirKhil/SI#150]
Здравствуйте. В программе SIQuester не работает импорт из базы вопросов (chgk.info).
Для решения данной проблемы можно изменить http на https в адресе.
В идеале лучше добавить в SIQuester возможность корректировать URL для импорта вопросов.

**Comment by VladimirKhil** [comment]
Fix будет в версии 5.10. Можно будет настраивать URL для подключения к Базе вопросов.
