### ISSUE TITLE
Хранение пакета в формате JSON

### ISSUE THREAD

**Issue by VladimirKhil** [VladimirKhil/SI#20]
Позволит проще открывать пакеты в веб-клиенте.
Но сейчас огромное количество пакетов уже создано в XML.
Так что если и браться за это, то будет длительный (несколько лет) переходный период, в течение которого пакеты будут содержать контент в двух форматах. И всё равно останется проблема старых непереконвертированных пакетов.
С другой стороны, XML в веб-клиенте можно спокойно читать.
Так что, возможно, переход не имеет смысла.
Обсуждаемо.

**Comment by tagrim** [comment]
Я думаю удобней всё-таки оставить as-is. 
JSON конечно хорошо, но для C# удобнее XML.

Если есть какая-то спека или дока, то проще написать конвертер. Онлайн или оффлайн. Я могу взять на себя веб/electron часть в принципе

**Comment by tagrim** [comment]
Ну и плюс, если запилить конвертер плагином, сможем подключить его в веб-части и по MIME определять, парсить его или скармливать как есть

**Comment by VladimirKhil** [comment]
Для C# в целом же без разницы, какой формат данных использовать. Конвертер на лету - хорошая идея. Но пока потребности в открытии пакетов в браузере нет, можно не торопиться :) Но в целом идея нормальная!
