### ISSUE TITLE
Переход на .NET 5

### ISSUE THREAD

**Issue by VladimirKhil** [VladimirKhil/SI#21]
Перейти с .NET Framework 4.6.1 на .NET Core 3.1. Интересное упражнение. Плюс должна повыситься производительность IO-операций.

**Comment by BadRyuner** [comment]
Может тогда перейти на .Net 6, когда он выйдет? Дальше с MAUI можно будет попробовать портировать приложение под Android/IOS/Linux.

**Comment by VladimirKhil** [comment]
> Может тогда перейти на .Net 6, когда он выйдет? Дальше с MAUI можно будет попробовать портировать приложение под Android/IOS/Linux.

Думаю, что перейти на .NET 6 уже потом не составит труда. Однако уже сейчас можно целиться в .NET 5, это верно.

**Comment by BadRyuner** [comment]
На .NET 5 не работает System.Speech.dll и из-за этого [тут](https://github.com/VladimirKhil/SI/blob/master/src/SICore/SICore/Clients/Viewer/ViewerHumanLogic.cs#L646) вылетает ошибка.
Также вылетает ошибка "configuration system failed to initialize" вот [тут](https://github.com/VladimirKhil/SI/blob/master/src/SIGame/SIGame/App.xaml.cs#L85) из-за [<system.diagnostics> с 18 по 25 строки](https://github.com/VladimirKhil/SI/blob/master/src/SIGame/SIGame/app.config#L18). Их удаление решает эту проблему, но наверное что-то из-за этого ломается, хоть и никаких ошибок больше не высвечивалось.

На .NET 5 надо переводить SIGAME, SIUI, SImulator и SIQuester?

**Comment by VladimirKhil** [comment]
> На .NET 5 не работает System.Speech.dll и из-за этого [тут](https://github.com/VladimirKhil/SI/blob/master/src/SICore/SICore/Clients/Viewer/ViewerHumanLogic.cs#L646) вылетает ошибка. Также отсутствуют ServiceBehavior и ServiceHost
> На .NET 5 надо переводить SIGAME, SIUI, SImulator и SIQuester?

Да, всё верно.

Безусловно, какую-то функциональность при переходе придётся потерять. WCF можно будет потом заменить на generic host.

**Comment by VladimirKhil** [comment]
Перешли на .NET 6.
