### ISSUE TITLE
SIQuester: [BUG] ошибочно пересчитывается базовая стоимость вопросов при перетаскивании

### ISSUE THREAD

**Issue by Mi-ch-ael** [VladimirKhil/SI#210]
Шаги воспроизведения:
* Создать пакет вопросов
* Назначить вопросам нестандартные стоимости, т.е. не равные Номер_раунда $\times$ Номер_вопроса $\times$ 100 (неважно, как: указанием другой базовой стоимости при создании пакета, вручную или кнопкой "Задать стоимости")
* Перетащить мышкой вопрос внутри темы с изменённой стоимостью

Результат: у всех вопросов в теме стоимость сбрасывается в значение Номер_раунда $\times$ Номер_вопроса $\times$ 100.
![GIF 12 03 2024 19-18-07](https://github.com/VladimirKhil/SI/assets/54897530/c40f2271-d72e-45d9-9201-352102d47e35)
Если перетаскивать вопрос из одной темы в другую, стоимость пересчитывается по умолчанию в обеих.

Ожидаемый результат: ранее заданные базовые стоимости вопросов не сбрасываются.

SIQuester 6.0.2
Windows 10 10.0.19045

**Comment by VladimirKhil** [comment]
@Mi-ch-ael выглядит так, что у вас выставлена в настройках галочка "Изменять стоимость вопросов при перетаскивании", которая и включает это поведение.

**Comment by Mi-ch-ael** [comment]
Да, настройка "Изменять стоимость вопросов при перетаскивании" включена, но по описанию не понятно, что она должна работать именно так. В 6.0.2 на русском всплывающая подсказка гласит "Вопросы будут перемещаться, а распределение стоимостей останется прежним". Но распределение стоимостей в теме на гифке не остаётся прежним: вместо 100 / 200 / 300 получается 200 / 400 / 600. Если эта настройка и должна себя вести так, как сейчас, то стоит изменить подсказку, чтобы было понятно, что стоимость пересчитывается исходя из номера раунда.

**Comment by VladimirKhil** [comment]
Теперь, начиная с версии 6.0.3, при перетаскивании сохраняются стоимости вопросов в теме, назначенные ранее.
