### ISSUE TITLE
Опечатка в документации (Протокол игры SIGame)

### ISSUE THREAD

**Issue by CrafterKolyan** [VladimirKhil/SI#25]
Ссылка на страницу:
https://github.com/VladimirKhil/SI/wiki/%D0%9F%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB-%D0%B8%D0%B3%D1%80%D1%8B-SIGame

В разделе **Сообщение**:
```
Text: основное содержимое сообщение.
```
заменить на
```
Text: основное содержимое сообщения.
```

**Comment by VladimirKhil** [comment]
Спасибо, поправил.
