### ISSUE TITLE
Кроссплатформенный клиент SIGame

### ISSUE THREAD

**Issue by kseniadumpling** [VladimirKhil/SI#26]
Добрый день!
Есть ли возможность собрать клиент SIGame под Linux?

**Comment by dimavoynov** [comment]
Здравствуйте, поддерживаю кроссплатформенную версию, веб-клиент не совсем удобен для пользования. 

Мне после некоторых допиливаний удалось поставить под вайном на убунте. С wine-mono не заводится, требует .net 4.6.1, хотя вроде бы текущая версия wine-mono его поддерживает. Требуется поставить dotnet461 через winetricks, тогда запускается. Но в целом работает нестабильно, падает с ошибками связанными с обработкой текста в поле ввода.

**Comment by VladimirKhil** [comment]
Здравствуйте! Да, через Wine можно пробовать, но это очень нестабильно. Гораздо лучше будет выпустить нормальную веб-версию.

**Comment by fiograf** [comment]
Здравстуйте! Можно открыть коды для веб-версии, чтобы её можно было дорабатывать?

**Comment by VladimirKhil** [comment]
> Здравстуйте! Можно открыть коды для веб-версии, чтобы её можно было дорабатывать?

Здравствуйте! Планирую так сделать. Но сейчас версия застряла на этапе переписывания на React, и в таком недоработанном виде её выкладывать не хочется.

**Comment by dimavoynov** [comment]
> Здравствуйте! Планирую так сделать. Но сейчас версия застряла на этапе переписывания на React, и в таком недоработанном виде её выкладывать не хочется.

Добрый день. Я правильное понимаю, что сейчас код для декстопа тоже не полностью выложен? У меня не получилось собрать.

Вы не могли бы написать инструкции как-чего компилить в каком порядке, чтобы в итоге рабочий клиент получался? Или может быть список того, что планируется добавить.

**Comment by VladimirKhil** [comment]
> > Здравствуйте! Планирую так сделать. Но сейчас версия застряла на этапе переписывания на React, и в таком недоработанном виде её выкладывать не хочется.
> 
> Добрый день. Я правильно понимаю, что сейчас код для декстопа тоже не полностью выложен? У меня не получилось собрать.
> 
> Вы не могли бы написать инструкции как-чего компилить в каком порядке, чтобы в итоге рабочий клиент получался? Или может быть список того, что планируется добавить.

Здравствуйте! Да, сейчас код выложен не весь. Планируется выложить всё, но после окультуривания.
По идее, выложенные проекты должны собираться. Какие возникают ошибки?

**Comment by dimavoynov** [comment]
> Здравствуйте! Да, сейчас код выложен не весь. Планируется выложить всё, но после окультуривания.
> По идее, выложенные проекты должны собираться. Какие возникают ошибки?

Не совсем точно выразился: разные проекты собираются по отдельности, но не ясно как отдельные части поженить друг с другом, так чтобы все работало как одно приложение.

**Comment by VladimirKhil** [comment]
> Не совсем точно выразился: разные проекты собираются по отдельности, но не ясно как отдельные части поженить друг с другом, так чтобы все работало как одно приложение.
Да, пока никак. Я постараюсь ускорить процесс публикования исходников.

**Comment by c3ffee** [comment]
Здравствуйте. На данный момент веб версия не работает с устройствами на IOS, можно ли это исправить? 
`Error: Failed to complete negotiation with the server: Error: Unauthorized`
`Error: Failed to start the connection: Error: Unauthorized`

**Comment by c3ffee** [comment]
Подебажил немного, на настройках по умолчанию сафари не передает куки в POST /sionline/negotiate.  
Нужно снять галочку с "Без перекрестн. отслеживания" - https://imgur.com/a/MDaUzl3

**Comment by VladimirKhil** [comment]
> Подебажил немного, на настройках по умолчанию сафари не передает куки в POST /sionline/negotiate.
> Нужно снять галочку с "Без перекрестн. отслеживания" - https://imgur.com/a/MDaUzl3

В новой версии веб-клиента, которая сейчас в работе, проблема с iOS исправлена. Авторизация выполняется не через куки, а через Url.

**Comment by dimavoynov** [comment]
Привествую энтузиастов, давайте создадим группу в телеграмме. Адрес @si-teleg, заходите товарищи. Владимир, добавьте в инфу о группе.

**Comment by KazankovMarch** [comment]
@dimavoynov есть ли какие-то наработки? В телеграме с таким юзенрнеймом людей не нашел :(

**Comment by dimavoynov** [comment]
> @dimavoynov есть ли какие-то наработки? В телеграме с таким юзенрнеймом людей не нашел :(

Нет, я пока занят был. Группа в телеге: https://teleg.run/siteleg

**Comment by VladimirKhil** [comment]
> Здравстуйте! Можно открыть коды для веб-версии, чтобы её можно было дорабатывать?

Веб-версия выложена в открытый доступ: https://github.com/VladimirKhil/SIOnline

**Comment by VladimirKhil** [comment]
Исходники десктопной версии также полностью выложены.

**Comment by VladimirKhil** [comment]
Закрываю issue, так как кроссплатформенный клиент реализуется в виде веб-версии.
