### ISSUE TITLE
Проблема музыкальных вопросов с кросс-платформенными играми

### ISSUE THREAD

**Issue by 7isenko** [VladimirKhil/SI#29]
Как воспроизводится:
1. Создается игра онлайн, в которой есть люди с десктоп-версии и хоть один из веб-версии. **Должны быть отключены фальстарты.**
2. Разыгрывается музыкальный вопрос.
3. Во время воспроизведения музыки кто-то отвечает на вопрос.

Что происходит:
У людей, играющих в десктоп-версии музыка прерывается, а в веб-версии не останавливатся.
Как правило, такая ошибка приводит к рассинхрону игрового времени, из-за чего у отвечающего человека может резко прерваться время ответа на вопрос, и начинается стадия выбора следующего вопроса. И эта стадия обычно "сломанная", и вопрос выбрать обычно никто, даже ведущий, не может.
Порой рассинхрон может привести и к более необычным последствиям.

**Comment by VladimirKhil** [comment]
Исправлено. Сервер обновлён.
