### ISSUE TITLE
кодировка файлов в архиве *.siq

### ISSUE THREAD

**Issue by centralhardware** [VladimirKhil/SI#61]
в какой кодировке кодируется zip архив файла пака игры sig?

**Comment by centralhardware** [comment]
имена файлов были в url encoded

**Comment by VladimirKhil** [comment]
> имена файлов были в url encoded

https://github.com/VladimirKhil/SI/wiki/%D0%A1%D0%BF%D0%B5%D1%86%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F-%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B0-.siq
