### ISSUE TITLE
SIGame: Переключения аудиоустройства

### ISSUE THREAD

**Issue by bagdenisov** [VladimirKhil/SI#63]
Здравствуйте! Я локальный стример, у которого виртуальным кабелем развязаны звуки голосовых приложении от других звуков компьютера, тем самым в поток идет только то, что мне нужно. В моменты, когда нужно записывать игру в SIGame, приходится включать общий звук, что не всегда удобно. Сторонние решения неудобны, а порой и все ломают.

Я предлагаю внедрить функцию переключения устройства вывода звука, предложив пользователю поставить вместо аудиоустройства по-умолчанию другое. Это может быть полезным во многих сферах, в том числе и системах с несколькими микшерными каналами звучания.

Спасибо!

**Comment by VladimirKhil** [comment]
Добрый день! Надеюсь, веб-версия решает эту проблему? В браузере больше опций для настройки аудио.
