### ISSUE TITLE
Добавление поддержки протокола https в SiGame и SiQuester

### ISSUE THREAD

**Issue by Sanchez4000** [VladimirKhil/SI#64]
Я конечно дико извиняюсь, но интернет уже достаточно давно перешел с обычного http на https. И поэтому ВСЕ хранилища файлов так же работают на https. Из этого возникает следующая проблема: если пакет вопросов слишком большой, то нет альтернативной возможности добавлять мультимедийный контент по внешней ссылке, хотя изначально такая возможность предполагалась.

**Comment by VladimirKhil** [comment]
Для достижения этого необходимо перевести проект на .NET 6. И поддержать XAML Islands. Текущая платформа HTTPS не поддерживает.

**Comment by VladimirKhil** [comment]
https://github.com/CommunityToolkit/Microsoft.Toolkit.Win32/issues/296

**Comment by VladimirKhil** [comment]
Альтернативный подход - встроить браузер для просмотра медиаконтента. Например, https://www.nuget.org/packages/CefSharp.WPF/ или WebView control.

**Comment by VladimirKhil** [comment]
https://www.nuget.org/packages/Vlc.DotNet.Wpf/

**Comment by VladimirKhil** [comment]
Оказывается, всё уже исправлено в .NET Core: https://github.com/dotnet/wpf/issues/722
Так что переходим на .NET 6, теперь без вариантов.

**Comment by VladimirKhil** [comment]
Исправлено в SIGame 7.6.0 и SIQuester 5.7.0.
