### ISSUE TITLE
Фора для отстающих игроков

### ISSUE THREAD

**Issue by Utilka** [VladimirKhil/SI#68]
Здравствуйте Владимир,

Мы с друзьями пришли к тому что когда один из игрков сильно вырывается вперед по очкам то остальные игроки понемногу выбиваются из игры. Начали вводить у себя в играх фору в виде того что что лидер ждет дополнительные пару секунд перед тем как кажимать на копку. Сработало! Отстающие игроки действительно стали включатся в игру.

Идея мне кажется достаточно хорошей чтобы ввести как опцию в найстройках игры.
Как бонус это помогает если один из игроков стабильно лучше попадает в тайминги нажатия на кнопку ответа чем другие.

Шутка в том что реализовать это строго математически немного сложнее чем с помощью чуйки которой мы руководствуемся обычно. Я подумал и вот к какой реализации пришел:
Идея в том что мы берем разницу между самым отстающим игроком и вырвавшимся вперед но не в очках а в вопросах необходимых для того чтобы долгнать лидера (если брать только очки то фору сложно адекватно реализовать)

"сколько вопросов нужно для того чтобы догнать лидера?" вопрос неоднозначный, но если в начале раунда узнать среднюю награду за вопрос и поделить разницу в очках на эту среднюю награду то выйдет неплохо

вот немного псевдокода накидал: 
```
average_reward_per_question = average (question_rewards_on_this_round) 
// e.g. average_reward_per_question =500
minimum_question_difference = 3 
// if player is leading for more questions than this value handicap should apply
time_per_question = 1 
// 1 second of handicap time per question above minimum_question_difference

question_lead_player_1 = (player_1_score - lowest_player_score) / average_reward_per_question 
// (7200-1700)/500 = 11

time_handicap_player_1  = (question_lead_player_1 - 3) * time_per_question 
// (11-3)*1 = 8

question_lead_player_2 = (player_2_score - lowest_player_score) / average_reward_per_question // (4200-1700)/500 = 5

time_handicap_player_2  = (question_lead_player_2 - 3) * time_per_question // (5-3)*1 = 2
```
опятьже средная награда за вопрос берется в начале раунда

фора которую дает каждый игрок - для каждого вопроса отдельно

неплохо что тут есть параметры которые ведущий может настроить перед созданием игры
также вероятно стоит добавить строчку для проверки не является ли время ожидания для лидирующего игрока больше чем возможное окно ответа. вообще лидеру нужно хотябы сколькото секунд на нажатие красной кнопки, в пседво коде я это обозначу minimal_answer_window

```
minimal_answ_window = 3 

if (time_handicap > time_to_press_red_button - minimal_answ_window):
	time_handicap = time_to_press_red_button - minimal_answ_window
```

time_handicap еще нужно будет округлять до нуля если его значение отрицательные 

В игре эту задержку можно визуализировать небольшой дополнительной полосой рядом с портретом лидирующего игрока.

Что думаете на счет всего этого Владимир?
Возможно когда-нибудь меня укусит неведомая мне муха я бы даже сам приложился бы к этому делу, но даже если так у меня на это уйдут недели если не месяц+, в отличии от человека который знает проект как свои пять пальцев.

**Comment by VladimirKhil** [comment]
Предложение хорошее. Но в игре уже есть настройка UsePingPenalty, которая просто не выведена в UI. Можете посмотреть в исходниках - мне кажется, это то, что нужно.
