### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by tagrim** [VladimirKhil/SI#7]
**1.** Оверлап кнопки и ника после апдейта

![image](https://user-images.githubusercontent.com/1091980/49394814-81599e80-f73d-11e8-878e-36bb4d0f10f8.png)

**2.** Предложение: может рамки для аватаров сделать одного размера?

**Comment by VladimirKhil** [comment]
1. Исправлено в 7.1.
2. Тогда получится, что аватары или растянуты, или в пустоте висят.
