### ISSUE TITLE
Что с сайтом?

### ISSUE THREAD

**Issue by fr00kt** [VladimirKhil/SI#9]
Скачать не возможно

**Comment by CrafterKolyan** [comment]
Прямые ссылки на скачивание:
SIGame (SIGame.Setup.exe): http://vladimirkhil.com/content/redist/si/game/SIGame.Setup.exe
SIQuester (SIQuester.Setup.exe): http://vladimirkhil.com/content/redist/si/siquester/SIQuester.Setup.exe
SImulator (SImulator.application): http://vladimirkhil.com/content/redist/si/simulator/SImulator.application
